# Generated by Django 6.0.6 on 2026-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_tbl',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
