# Generated by Django 4.2.7 on 2026-07-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=100)),
                ('cake_price', models.PositiveIntegerField()),
                ('cake_description', models.TextField(blank=True)),
                ('cake_category', models.CharField(choices=[('vanila', 'vanila'), ('chocolate', 'chocolate'), ('starwberry', 'starwberry'), ('cheese', 'cheese'), ('others', 'others')], default='others', max_length=100)),
                ('cake_image', models.FileField(upload_to='images')),
            ],
        ),
    ]
